#ifndef CONSTANTS_H_INCLUDED
#define CONSTANTS_H_INCLUDED

#define SIZE_BLOCK 48
#define N_BLOCKS_X 16
#define N_BLOCKS_Y 16
#define WINDOW_WIDTH N_BLOCKS_X * SIZE_BLOCK
#define WINDOW_HEIGHT N_BLOCKS_Y * SIZE_BLOCK

#endif // CONSTANTS_H_INCLUDED
