#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_RELEASE = $(INC) -I/usr/local/include/
CFLAGS_RELEASE = $(CFLAGS) -O3 -Wunreachable-code -Wextra -Wall -std=c99
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR) -L/usr/lib/x86_64-linux-gnu/
LIB_RELEASE = $(LIB)-lSDL2-2.0
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/game

OBJ_RELEASE = $(OBJDIR_RELEASE)/character.o $(OBJDIR_RELEASE)/engine.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/map.o

all: release

clean: clean_release

before_release: 
	cbp2make -in game.cbp -out Makefile
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/character.o: character.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c character.c -o $(OBJDIR_RELEASE)/character.o

$(OBJDIR_RELEASE)/engine.o: engine.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c engine.c -o $(OBJDIR_RELEASE)/engine.o

$(OBJDIR_RELEASE)/main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/map.o: map.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c map.c -o $(OBJDIR_RELEASE)/map.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_release after_release clean_release

